name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy=1.26.4
  - pandas
  - bqplot
  - ipywidgets
  - ipyleaflet
  - plotly
  - nbformat
