name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0'
          environment-file: 'build-environment.yml'

      - name: Build the JupyterLite site
        shell: bash -l {0}
        run: voici build --contents content --output-dir dist

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4  # Correct version for uploading
        with:
          name: github-pages
          path: ./dist  # Ensure this matches your build output

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        run: |
          # Deploying files from /dist to GitHub Pages directly
          cp -r ./dist/* ./docs  # or another deployment command you wish to use
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin main  # Pushes to the main branch (can be gh-pages if desired)
